const envKey = {
  BASE_URL_USER: process.env.REACT_APP_BASE_URL_USER,
  BASE_URL_COOPERATIVE: process.env.REACT_APP_BASE_URL_COOPERATIVE,
  BASE_URL_CLIENT: process.env.REACT_APP_BASE_URL_CLIENT,
  COOPERATIVE_API_KEY: process.env.REACT_APP_COOPERATIVE_API_KEY,
  COOPERATIVE_V1: process.env.REACT_APP_COOPERATIVE_V1
};

module.exports = envKey;
